// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ilyakaznacheev/roster/internal/api/models"
)

// PostRegisterCreatedCode is the HTTP code returned for type PostRegisterCreated
const PostRegisterCreatedCode int = 201

/*PostRegisterCreated created

swagger:response postRegisterCreated
*/
type PostRegisterCreated struct {
}

// NewPostRegisterCreated creates PostRegisterCreated with default headers values
func NewPostRegisterCreated() *PostRegisterCreated {

	return &PostRegisterCreated{}
}

// WriteResponse to the client
func (o *PostRegisterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostRegisterConflictCode is the HTTP code returned for type PostRegisterConflict
const PostRegisterConflictCode int = 409

/*PostRegisterConflict conflict

swagger:response postRegisterConflict
*/
type PostRegisterConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostRegisterConflict creates PostRegisterConflict with default headers values
func NewPostRegisterConflict() *PostRegisterConflict {

	return &PostRegisterConflict{}
}

// WithPayload adds the payload to the post register conflict response
func (o *PostRegisterConflict) WithPayload(payload *models.Error) *PostRegisterConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register conflict response
func (o *PostRegisterConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegisterInternalServerErrorCode is the HTTP code returned for type PostRegisterInternalServerError
const PostRegisterInternalServerErrorCode int = 500

/*PostRegisterInternalServerError internal server error

swagger:response postRegisterInternalServerError
*/
type PostRegisterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostRegisterInternalServerError creates PostRegisterInternalServerError with default headers values
func NewPostRegisterInternalServerError() *PostRegisterInternalServerError {

	return &PostRegisterInternalServerError{}
}

// WithPayload adds the payload to the post register internal server error response
func (o *PostRegisterInternalServerError) WithPayload(payload *models.Error) *PostRegisterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register internal server error response
func (o *PostRegisterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
