version: "3"

services:
  mongo:
    image: mongo:3.4.8
    ports:
      - "27018:27017"
    expose:
      - "27017"
    environment:
#      - MONGO_INITDB_ROOT_USERNAME=roster
#      - MONGO_INITDB_ROOT_PASSWORD=roster
      - MONGO_INITDB_DATABASE=roster
    volumes:
      #      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./temp/mongodb:/data/db
    command: mongod

  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo