// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RearrangeRequest rearrange request
// swagger:model RearrangeRequest
type RearrangeRequest struct {

	// to active
	ToActive []int64 `json:"to_active"`

	// to benched
	ToBenched []int64 `json:"to_benched"`
}

// Validate validates this rearrange request
func (m *RearrangeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RearrangeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RearrangeRequest) UnmarshalBinary(b []byte) error {
	var res RearrangeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
