// Code generated by go-swagger; DO NOT EDIT.

package roster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRostersHandlerFunc turns a function with the right signature into a get rosters handler
type GetRostersHandlerFunc func(GetRostersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRostersHandlerFunc) Handle(params GetRostersParams) middleware.Responder {
	return fn(params)
}

// GetRostersHandler interface for that can handle valid get rosters params
type GetRostersHandler interface {
	Handle(GetRostersParams) middleware.Responder
}

// NewGetRosters creates a new http.Handler for the get rosters operation
func NewGetRosters(ctx *middleware.Context, handler GetRostersHandler) *GetRosters {
	return &GetRosters{Context: ctx, Handler: handler}
}

/*GetRosters swagger:route GET /rosters roster getRosters

Get a list of rosters

Returns a full list of rosters on the server

*/
type GetRosters struct {
	Context *middleware.Context
	Handler GetRostersHandler
}

func (o *GetRosters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRostersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
