// Code generated by go-swagger; DO NOT EDIT.

package roster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRosterRosteridParams creates a new GetRosterRosteridParams object
// no default values defined in spec.
func NewGetRosterRosteridParams() GetRosterRosteridParams {

	return GetRosterRosteridParams{}
}

// GetRosterRosteridParams contains all the bound params for the get roster rosterid operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetRosterRosterid
type GetRosterRosteridParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Rosterid string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRosterRosteridParams() beforehand.
func (o *GetRosterRosteridParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRosterid, rhkRosterid, _ := route.Params.GetOK("rosterid")
	if err := o.bindRosterid(rRosterid, rhkRosterid, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRosterid binds and validates parameter Rosterid from path.
func (o *GetRosterRosteridParams) bindRosterid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Rosterid = raw

	return nil
}
