// Code generated by go-swagger; DO NOT EDIT.

package roster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRosterRosteridActiveHandlerFunc turns a function with the right signature into a get roster rosterid active handler
type GetRosterRosteridActiveHandlerFunc func(GetRosterRosteridActiveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRosterRosteridActiveHandlerFunc) Handle(params GetRosterRosteridActiveParams) middleware.Responder {
	return fn(params)
}

// GetRosterRosteridActiveHandler interface for that can handle valid get roster rosterid active params
type GetRosterRosteridActiveHandler interface {
	Handle(GetRosterRosteridActiveParams) middleware.Responder
}

// NewGetRosterRosteridActive creates a new http.Handler for the get roster rosterid active operation
func NewGetRosterRosteridActive(ctx *middleware.Context, handler GetRosterRosteridActiveHandler) *GetRosterRosteridActive {
	return &GetRosterRosteridActive{Context: ctx, Handler: handler}
}

/*GetRosterRosteridActive swagger:route GET /roster/{rosterid}/active roster getRosterRosteridActive

Get a roster with active players only

Returns a roster with active playes only

*/
type GetRosterRosteridActive struct {
	Context *middleware.Context
	Handler GetRosterRosteridActiveHandler
}

func (o *GetRosterRosteridActive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRosterRosteridActiveParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
