// Code generated by go-swagger; DO NOT EDIT.

package roster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ilyakaznacheev/roster/internal/models"
)

// GetRosterOKCode is the HTTP code returned for type GetRosterOK
const GetRosterOKCode int = 200

/*GetRosterOK successful operation

swagger:response getRosterOK
*/
type GetRosterOK struct {

	/*
	  In: Body
	*/
	Payload models.AllRosters `json:"body,omitempty"`
}

// NewGetRosterOK creates GetRosterOK with default headers values
func NewGetRosterOK() *GetRosterOK {

	return &GetRosterOK{}
}

// WithPayload adds the payload to the get roster o k response
func (o *GetRosterOK) WithPayload(payload models.AllRosters) *GetRosterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get roster o k response
func (o *GetRosterOK) SetPayload(payload models.AllRosters) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRosterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllRosters{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRosterInternalServerErrorCode is the HTTP code returned for type GetRosterInternalServerError
const GetRosterInternalServerErrorCode int = 500

/*GetRosterInternalServerError internal server error

swagger:response getRosterInternalServerError
*/
type GetRosterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRosterInternalServerError creates GetRosterInternalServerError with default headers values
func NewGetRosterInternalServerError() *GetRosterInternalServerError {

	return &GetRosterInternalServerError{}
}

// WithPayload adds the payload to the get roster internal server error response
func (o *GetRosterInternalServerError) WithPayload(payload *models.Error) *GetRosterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get roster internal server error response
func (o *GetRosterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRosterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
