// Code generated by go-swagger; DO NOT EDIT.

package roster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ilyakaznacheev/roster/internal/api/models"
)

// GetRostersOKCode is the HTTP code returned for type GetRostersOK
const GetRostersOKCode int = 200

/*GetRostersOK successful operation

swagger:response getRostersOK
*/
type GetRostersOK struct {

	/*
	  In: Body
	*/
	Payload models.AllRosters `json:"body,omitempty"`
}

// NewGetRostersOK creates GetRostersOK with default headers values
func NewGetRostersOK() *GetRostersOK {

	return &GetRostersOK{}
}

// WithPayload adds the payload to the get rosters o k response
func (o *GetRostersOK) WithPayload(payload models.AllRosters) *GetRostersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rosters o k response
func (o *GetRostersOK) SetPayload(payload models.AllRosters) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRostersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllRosters{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRostersInternalServerErrorCode is the HTTP code returned for type GetRostersInternalServerError
const GetRostersInternalServerErrorCode int = 500

/*GetRostersInternalServerError internal server error

swagger:response getRostersInternalServerError
*/
type GetRostersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRostersInternalServerError creates GetRostersInternalServerError with default headers values
func NewGetRostersInternalServerError() *GetRostersInternalServerError {

	return &GetRostersInternalServerError{}
}

// WithPayload adds the payload to the get rosters internal server error response
func (o *GetRostersInternalServerError) WithPayload(payload *models.Error) *GetRostersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rosters internal server error response
func (o *GetRostersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRostersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
