// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ilyakaznacheev/roster/internal/api/restapi/operations/auth"
	"github.com/ilyakaznacheev/roster/internal/api/restapi/operations/player"
	"github.com/ilyakaznacheev/roster/internal/api/restapi/operations/roster"
)

// NewRosterAPI creates a new Roster instance
func NewRosterAPI(spec *loads.Document) *RosterAPI {
	return &RosterAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		RosterGetRostersHandler: roster.GetRostersHandlerFunc(func(params roster.GetRostersParams) middleware.Responder {
			return middleware.NotImplemented("operation RosterGetRosters has not yet been implemented")
		}),
		RosterGetRostersIDHandler: roster.GetRostersIDHandlerFunc(func(params roster.GetRostersIDParams) middleware.Responder {
			return middleware.NotImplemented("operation RosterGetRostersID has not yet been implemented")
		}),
		RosterGetRostersIDActiveHandler: roster.GetRostersIDActiveHandlerFunc(func(params roster.GetRostersIDActiveParams) middleware.Responder {
			return middleware.NotImplemented("operation RosterGetRostersIDActive has not yet been implemented")
		}),
		RosterGetRostersIDBenchedHandler: roster.GetRostersIDBenchedHandlerFunc(func(params roster.GetRostersIDBenchedParams) middleware.Responder {
			return middleware.NotImplemented("operation RosterGetRostersIDBenched has not yet been implemented")
		}),
		AuthPostLoginHandler: auth.PostLoginHandlerFunc(func(params auth.PostLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation AuthPostLogin has not yet been implemented")
		}),
		AuthPostRegisterHandler: auth.PostRegisterHandlerFunc(func(params auth.PostRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation AuthPostRegister has not yet been implemented")
		}),
		PlayerPostRostersIDAddPlayerHandler: player.PostRostersIDAddPlayerHandlerFunc(func(params player.PostRostersIDAddPlayerParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation PlayerPostRostersIDAddPlayer has not yet been implemented")
		}),
		PlayerPostRostersIDRearrangeHandler: player.PostRostersIDRearrangeHandlerFunc(func(params player.PostRostersIDRearrangeParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation PlayerPostRostersIDRearrange has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (Bearer) Authorization from header param [Authorization] has not yet been implemented")
		},

		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*RosterAPI Roster Service API */
type RosterAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// BearerAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// RosterGetRostersHandler sets the operation handler for the get rosters operation
	RosterGetRostersHandler roster.GetRostersHandler
	// RosterGetRostersIDHandler sets the operation handler for the get rosters ID operation
	RosterGetRostersIDHandler roster.GetRostersIDHandler
	// RosterGetRostersIDActiveHandler sets the operation handler for the get rosters ID active operation
	RosterGetRostersIDActiveHandler roster.GetRostersIDActiveHandler
	// RosterGetRostersIDBenchedHandler sets the operation handler for the get rosters ID benched operation
	RosterGetRostersIDBenchedHandler roster.GetRostersIDBenchedHandler
	// AuthPostLoginHandler sets the operation handler for the post login operation
	AuthPostLoginHandler auth.PostLoginHandler
	// AuthPostRegisterHandler sets the operation handler for the post register operation
	AuthPostRegisterHandler auth.PostRegisterHandler
	// PlayerPostRostersIDAddPlayerHandler sets the operation handler for the post rosters ID add player operation
	PlayerPostRostersIDAddPlayerHandler player.PostRostersIDAddPlayerHandler
	// PlayerPostRostersIDRearrangeHandler sets the operation handler for the post rosters ID rearrange operation
	PlayerPostRostersIDRearrangeHandler player.PostRostersIDRearrangeHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *RosterAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *RosterAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *RosterAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *RosterAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *RosterAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *RosterAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *RosterAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the RosterAPI
func (o *RosterAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.RosterGetRostersHandler == nil {
		unregistered = append(unregistered, "roster.GetRostersHandler")
	}

	if o.RosterGetRostersIDHandler == nil {
		unregistered = append(unregistered, "roster.GetRostersIDHandler")
	}

	if o.RosterGetRostersIDActiveHandler == nil {
		unregistered = append(unregistered, "roster.GetRostersIDActiveHandler")
	}

	if o.RosterGetRostersIDBenchedHandler == nil {
		unregistered = append(unregistered, "roster.GetRostersIDBenchedHandler")
	}

	if o.AuthPostLoginHandler == nil {
		unregistered = append(unregistered, "auth.PostLoginHandler")
	}

	if o.AuthPostRegisterHandler == nil {
		unregistered = append(unregistered, "auth.PostRegisterHandler")
	}

	if o.PlayerPostRostersIDAddPlayerHandler == nil {
		unregistered = append(unregistered, "player.PostRostersIDAddPlayerHandler")
	}

	if o.PlayerPostRostersIDRearrangeHandler == nil {
		unregistered = append(unregistered, "player.PostRostersIDRearrangeHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *RosterAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *RosterAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {

		case "Bearer":

			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.BearerAuth)

		}
	}
	return result

}

// Authorizer returns the registered authorizer
func (o *RosterAPI) Authorizer() runtime.Authorizer {

	return o.APIAuthorizer

}

// ConsumersFor gets the consumers for the specified media types
func (o *RosterAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *RosterAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *RosterAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the roster API
func (o *RosterAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *RosterAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/rosters"] = roster.NewGetRosters(o.context, o.RosterGetRostersHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/rosters/{id}"] = roster.NewGetRostersID(o.context, o.RosterGetRostersIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/rosters/{id}/active"] = roster.NewGetRostersIDActive(o.context, o.RosterGetRostersIDActiveHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/rosters/{id}/benched"] = roster.NewGetRostersIDBenched(o.context, o.RosterGetRostersIDBenchedHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = auth.NewPostLogin(o.context, o.AuthPostLoginHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/register"] = auth.NewPostRegister(o.context, o.AuthPostRegisterHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/rosters/{id}/add_player"] = player.NewPostRostersIDAddPlayer(o.context, o.PlayerPostRostersIDAddPlayerHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/rosters/{id}/rearrange"] = player.NewPostRostersIDRearrange(o.context, o.PlayerPostRostersIDRearrangeHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *RosterAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *RosterAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *RosterAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *RosterAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
