name: Go
on: [push]
jobs:

  build:
    name: Test
    runs-on:
      - macos-latest
      - ubuntu-latest
    strategy:
      matrix:
        go: ['1.13.x']
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Tests
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
