// Code generated by go-swagger; DO NOT EDIT.

package player

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostRostersIDRearrangeHandlerFunc turns a function with the right signature into a post rosters ID rearrange handler
type PostRostersIDRearrangeHandlerFunc func(PostRostersIDRearrangeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRostersIDRearrangeHandlerFunc) Handle(params PostRostersIDRearrangeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRostersIDRearrangeHandler interface for that can handle valid post rosters ID rearrange params
type PostRostersIDRearrangeHandler interface {
	Handle(PostRostersIDRearrangeParams, interface{}) middleware.Responder
}

// NewPostRostersIDRearrange creates a new http.Handler for the post rosters ID rearrange operation
func NewPostRostersIDRearrange(ctx *middleware.Context, handler PostRostersIDRearrangeHandler) *PostRostersIDRearrange {
	return &PostRostersIDRearrange{Context: ctx, Handler: handler}
}

/*PostRostersIDRearrange swagger:route POST /rosters/{id}/rearrange player postRostersIdRearrange

Rearrange players

Changes player group arrangement

*/
type PostRostersIDRearrange struct {
	Context *middleware.Context
	Handler PostRostersIDRearrangeHandler
}

func (o *PostRostersIDRearrange) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostRostersIDRearrangeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
