// Code generated by go-swagger; DO NOT EDIT.

package player

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostRosterRosteridRearrangeHandlerFunc turns a function with the right signature into a post roster rosterid rearrange handler
type PostRosterRosteridRearrangeHandlerFunc func(PostRosterRosteridRearrangeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRosterRosteridRearrangeHandlerFunc) Handle(params PostRosterRosteridRearrangeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRosterRosteridRearrangeHandler interface for that can handle valid post roster rosterid rearrange params
type PostRosterRosteridRearrangeHandler interface {
	Handle(PostRosterRosteridRearrangeParams, interface{}) middleware.Responder
}

// NewPostRosterRosteridRearrange creates a new http.Handler for the post roster rosterid rearrange operation
func NewPostRosterRosteridRearrange(ctx *middleware.Context, handler PostRosterRosteridRearrangeHandler) *PostRosterRosteridRearrange {
	return &PostRosterRosteridRearrange{Context: ctx, Handler: handler}
}

/*PostRosterRosteridRearrange swagger:route POST /roster/{rosterid}/rearrange player postRosterRosteridRearrange

Rearrange players

Changes player group arrangement

*/
type PostRosterRosteridRearrange struct {
	Context *middleware.Context
	Handler PostRosterRosteridRearrangeHandler
}

func (o *PostRosterRosteridRearrange) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostRosterRosteridRearrangeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
