// Code generated by go-swagger; DO NOT EDIT.

package player

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ilyakaznacheev/roster/internal/models"
)

// PostRostersIDRearrangeOKCode is the HTTP code returned for type PostRostersIDRearrangeOK
const PostRostersIDRearrangeOKCode int = 200

/*PostRostersIDRearrangeOK successful operation

swagger:response postRostersIdRearrangeOK
*/
type PostRostersIDRearrangeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Roster `json:"body,omitempty"`
}

// NewPostRostersIDRearrangeOK creates PostRostersIDRearrangeOK with default headers values
func NewPostRostersIDRearrangeOK() *PostRostersIDRearrangeOK {

	return &PostRostersIDRearrangeOK{}
}

// WithPayload adds the payload to the post rosters Id rearrange o k response
func (o *PostRostersIDRearrangeOK) WithPayload(payload *models.Roster) *PostRostersIDRearrangeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rosters Id rearrange o k response
func (o *PostRostersIDRearrangeOK) SetPayload(payload *models.Roster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRostersIDRearrangeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRostersIDRearrangeForbiddenCode is the HTTP code returned for type PostRostersIDRearrangeForbidden
const PostRostersIDRearrangeForbiddenCode int = 403

/*PostRostersIDRearrangeForbidden forbidden

swagger:response postRostersIdRearrangeForbidden
*/
type PostRostersIDRearrangeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostRostersIDRearrangeForbidden creates PostRostersIDRearrangeForbidden with default headers values
func NewPostRostersIDRearrangeForbidden() *PostRostersIDRearrangeForbidden {

	return &PostRostersIDRearrangeForbidden{}
}

// WithPayload adds the payload to the post rosters Id rearrange forbidden response
func (o *PostRostersIDRearrangeForbidden) WithPayload(payload *models.Error) *PostRostersIDRearrangeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rosters Id rearrange forbidden response
func (o *PostRostersIDRearrangeForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRostersIDRearrangeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRostersIDRearrangeNotFoundCode is the HTTP code returned for type PostRostersIDRearrangeNotFound
const PostRostersIDRearrangeNotFoundCode int = 404

/*PostRostersIDRearrangeNotFound not found

swagger:response postRostersIdRearrangeNotFound
*/
type PostRostersIDRearrangeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostRostersIDRearrangeNotFound creates PostRostersIDRearrangeNotFound with default headers values
func NewPostRostersIDRearrangeNotFound() *PostRostersIDRearrangeNotFound {

	return &PostRostersIDRearrangeNotFound{}
}

// WithPayload adds the payload to the post rosters Id rearrange not found response
func (o *PostRostersIDRearrangeNotFound) WithPayload(payload *models.Error) *PostRostersIDRearrangeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rosters Id rearrange not found response
func (o *PostRostersIDRearrangeNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRostersIDRearrangeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRostersIDRearrangeInternalServerErrorCode is the HTTP code returned for type PostRostersIDRearrangeInternalServerError
const PostRostersIDRearrangeInternalServerErrorCode int = 500

/*PostRostersIDRearrangeInternalServerError internal server error

swagger:response postRostersIdRearrangeInternalServerError
*/
type PostRostersIDRearrangeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostRostersIDRearrangeInternalServerError creates PostRostersIDRearrangeInternalServerError with default headers values
func NewPostRostersIDRearrangeInternalServerError() *PostRostersIDRearrangeInternalServerError {

	return &PostRostersIDRearrangeInternalServerError{}
}

// WithPayload adds the payload to the post rosters Id rearrange internal server error response
func (o *PostRostersIDRearrangeInternalServerError) WithPayload(payload *models.Error) *PostRostersIDRearrangeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rosters Id rearrange internal server error response
func (o *PostRostersIDRearrangeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRostersIDRearrangeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
